version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.0.1

jobs:
  lint:
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run: node --version
      - run:
          name: Install NPM dependencies
          command: |
            npm install
      - run:
          name: "Build"
          command: |
            npm run build
      - run:
          name: "Lint"
          command: |
            npm run lint
  test:
    steps:
      - checkout
      - run:
          name: Install NPM dependencies
          command: |
            npm install
      - run:
          name: "Build"
          command: |
            npm run build
      - run:
          name: "Test"
          command: |
            npm run test
  deploy:
      machine: true
      steps:
        - checkout
        - run:
            name: Build and push Docker image to Heroku
            command: |
              sudo curl https://cli-assets.heroku.com/install.sh | sh
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a veekz/m2-secure-coding-app web
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a veekz/m2-secure-coding-app web
workflows:
  lint-test-build-deploy:
    jobs: 
      - lint
      - test
      - docker/publish:
          deploy: false
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - deploy:
          requires:
            - lint
            - test
            - docker/publish
          filters:
            branches:
              only: master
